use_frameworks!

platform :ios, '8.0'

target 'UserCenterModule_Example' do
  pod 'UserCenterModule', :path => '../'

  target 'UserCenterModule_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
